services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_sqs
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh"

  worker:
    build: .
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=virtual
      - SQS_ENDPOINT=http://localstack:4566
      - QUEUE_URL=http://localstack:4566/000000000000/teste-fila
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  worker-simple:
    build: .
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=simple
      - SQS_ENDPOINT=http://localstack:4566
      - QUEUE_URL=http://localstack:4566/000000000000/teste-fila-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  default:
    name: sqs_network